baseURL = 'https://sap218.uk/'
languageCode = 'en-us'
title = 'sap218'
theme = 'mono'
#googleAnalytics = "xxx"

#ignoreLogs = ['warning-goldmark-raw-html'] 

[params]
author = "sap218"
description = "a site"
enable_toc = false
enable_collapsible_toc = true
enable_collapsible_changelogs = true
footer = "Copyright © sap218"
enable_site_search = true 
enable_zooming_js = false # to make true for particular pages if need
enable_math = false # same as above

[outputs]
home = ["HTML", "RSS", "JSON"]

[params.list_layout]
enable_group_by_year = true 
enable_show_date = true 
enable_pagination = true 

###################

[[menu.navbar]]
identifier = "about"
name = "about"
url = "/about/"
weight = 1

[[menu.navbar]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 2

[[menu.navbar]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 3

[[menu.navbar]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 4

[[menu.navbar]]
identifier = "random"
name = "|  random"
url = "/random/"
weight = 5

# end of page