baseURL = 'https://sap218.uk/'
languageCode = 'en-us'
title = 'sap218'
theme = 'mono'
googleAnalytics = "xxx"


[params]
author = "sap218"
description = "blog site"
#enable_toc = true
#enable_collapsible_toc = true
#enable_collapsible_changelogs = true
footer = "Copyright © 2023 by sap218"
enable_math = true 
enable_site_search = true 

[outputs]
home = ["HTML", "RSS", "JSON"]

[params.list_layout]
enable_group_by_year = true 
enable_show_date = true 
enable_pagination = false 





[[menu.navbar]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = -100

[[menu.navbar]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 100

[[menu.navbar]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = -20

[[menu.navbar]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 80